packages:
  - packages/*
catalog:
  '@antfu/eslint-config': ^6.1.0
  '@babel/types': ^7.28.5
  '@microsoft/api-extractor': ^7.52.8
  '@rslib/core': ^0.8.0
  '@types/node': ^22.18.12
  '@unocss/reset': ^66.5.4
  '@unocss/transformer-directives': ^66.5.4
  '@unocss/transformer-variant-group': ^66.5.4
  '@vitejs/plugin-basic-ssl': ^2.1.0
  '@vitejs/plugin-vue': ^6.0.1
  '@vitest/ui': ^4.0.4
  '@vue/compiler-sfc': ^3.5.22
  '@vue/test-utils': ^2.4.6
  '@vueuse/core': ^14.0.0
  bumpp: ^10.3.1
  changelogen: ^0.6.2
  eslint: ^9.38.0
  highlight.js: ^11.11.1
  jsdom: ^27.0.1
  lightningcss: ^1.30.2
  lint-staged: ^16.2.6
  markdown-it-anchor: ^9.2.0
  pnpm: ^10.19.0
  pre-commit: ^1.2.2
  simple-git-hooks: ^2.13.1
  taze: ^19.8.1
  terser: ^5.44.0
  tsdown: ^0.15.10
  typescript: ^5.9.3
  unocss: ^66.5.4
  unplugin-auto-import: ^20.2.0
  unplugin-icons: ^22.5.0
  unplugin-vue-components: ^30.0.0
  unplugin-vue-inspector: ^2.3.2
  unplugin-vue-markdown: ^29.2.0
  vite: ^7.1.12
  vite-plugin-css-injected-by-js: ^3.5.2
  vite-plugin-dts: ^4.5.4
  vite-plugin-pages: ^0.33.1
  vite-plugin-vue-devtools: ^8.0.3
  vitest: ^4.0.4
  vue: ^3.5.22
  vue-router: ^4.6.3
  vue-tsc: ^3.1.2
  vue-typegen: ^0.2.0
